spring.application.name=m5-level-22

# Приветствие – вынесено в проперти, чтобы можно было переопределить через ENV в Docker:
#   APP_GREETING="Привет из контейнера!"
# Spring Boot подхватит APP_GREETING -> app.greeting автоматически.
app.greeting=Hello World!

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

spring.jpa.hibernate.ddl-auto=update
